version: "3"

services:
  nuxt:
    image: node
    ports:
      - "3000:3000"
    working_dir: /home/node/app
    volumes:
      - ./components:/home/node/app/components:ro
      - ./layouts:/home/node/app/layouts:ro
      - ./pages:/home/node/app/pages:ro
      - ./store:/home/node/app/store:ro
      - ./nuxt.config.js:/home/node/app/nuxt.config.js:ro
      - ./package.json:/home/node/app/package.json:ro
      - ./package-lock.json:/home/node/app/package-lock.json
    command: npm run dev:docker

  webdav:
    build: ./webdav_debug_server
    ports:
      - "3001:80"
    volumes:
      - ./webdav_debug_server/storage:/media
      - ./webdav_debug_server/nginx.conf:/etc/nginx/conf.d/default.conf:ro
