version: "3"

services:
  nuxt:
    image: node
    ports:
      - "3000:3000"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: npm run dev:docker

  webdav:
    build: ./webdav_debug_server
    ports:
      - "3001:80"
    volumes:
      - ./webdav_debug_server/storage:/media
      - ./webdav_debug_server/nginx.conf:/etc/nginx/conf.d/default.conf:ro
